<div id="order">
	<h2><?php echo $this->translate('Order') . ' ' . $this->order->getOrderId();?></h2>
	<div class="details">
		<div class="client">
			<h3><?php echo $this->translate('Client details'); ?></h3>
			<dl>
				<dt><?php echo $this->translate('First name'); ?></dt>
				<dd><?php echo $this->client->getFirstName();?></dd>
				<dt><?php echo $this->translate('Last name'); ?></dt>
				<dd><?php echo $this->client->getLastName();?></dd>
				<dt><?php echo $this->translate('Email'); ?></dt>
				<dd><?php echo $this->client->getEmail();?></dd>
				<dt><?php echo $this->translate('Phone'); ?></dt>
				<dd><?php echo $this->client->getPhone();?></dd>
			</dl>


		</div>
		<div class="company">
			<h3><?php echo $this->translate('Company details'); ?></h3>
			<dl>
				<dt><?php echo $this->translate('Name'); ?></dt>
				<dd><?php echo $this->company->getName();?></dd>
				<dt><?php echo $this->translate('Country'); ?></dt>
				<dd><?php echo $this->company->getCountry();?></dd>
				<dt><?php echo $this->translate('Email'); ?></dt>
				<dd><?php echo $this->company->getEmail();?></dd>
				<dt><?php echo $this->translate('Phone'); ?></dt>
				<dd><?php echo $this->company->getPhone();?></dd>
				<dt><?php echo $this->translate('Reg Number'); ?></dt>
				<dd><?php echo $this->company->getRegNumber();?></dd>
				<dt><?php echo $this->translate('VAT Number'); ?></dt>
				<dd><?php echo $this->company->getVatNumber();?></dd>
				<dt><?php echo $this->translate('Address'); ?></dt>
				<dd><?php echo $this->company->getAddress();?></dd>
				<dt><?php echo $this->translate('Bank name'); ?></dt>
				<dd><?php echo $this->company->getBankName();?></dd>
				<dt><?php echo $this->translate('Bank account'); ?></dt>
				<dd><?php echo $this->company->getBankAccount();?></dd>
			</dl>
		</div>
		<div class="shipping">
			<h3><?php echo $this->translate('Shipping details'); ?></h3>
			<dl>
				<dt><?php echo $this->translate('Country'); ?></dt>
				<dd><?php echo $this->translate($this->shipping_address->getCountry());?></dd>
				<dt><?php echo $this->translate('Address'); ?></dt>
				<dd><?php echo $this->shipping_address->getAddress();?></dd>
				<dt><?php echo $this->translate('Address2'); ?></dt>
				<dd><?php echo $this->shipping_address->getAddress2();?></dd>
				<dt><?php echo $this->translate('Zip code'); ?></dt>
				<dd><?php echo $this->shipping_address->getZipCode();?>&nbsp;</dd>
				<dt><?php echo $this->translate('Phone'); ?></dt>
				<dd><?php echo $this->shipping_address->getPhone();?></dd>
			</dl>
		</div>

	</div>
	<div class="clear"></div>
	<div class="items">
		<h3><?php echo $this->translate('Order items'); ?></h3>

		<table>
			<tr>
				<th></th>
				<th></th>
				<th></th>
				<th></th>
				<th><?php echo $this->translate('Amount'); ?></th>
				<th><?php echo $this->translate('Price'); ?></th>
				<th><?php echo $this->translate('Total'); ?></th>
			</tr>
			<?php 
				$totalPrice = 0;
				$totalAmount = 0;
				foreach($this->items as $item):?>
			<?php $itemInfo = $item->getTdInfo();?>
			<tr>
				<td><?php echo $itemInfo['ART_ID'];?></td>
				<td><?php echo $itemInfo['ART_ARTICLE_NR'];?></td>
				<td><?php echo $itemInfo['SUP_BRAND'];?></td>
				<td><?php echo $itemInfo['ART_COMPLETE_DES_TEXT'];?></td>

				<td><?php echo $item->getAmount(); $totalAmount+=$item->getAmount();?></td>
				<td><?php echo $item->getPrice(); $totalPrice+=($item->getPrice()*$item->getAmount());?></td>
				<td><?php echo $item->getPrice()*$item->getAmount();?></td>

			</tr>
			<?php endforeach;?>
			<tr class="total">
				<td></td>
				<td></td>
				<td></td>
				<td align="right"><?php echo $this->translate('Total'); ?></td>
				<td><?php echo $totalAmount;?></td>
				<td></td>
				<td><?php echo $totalPrice;?></td>
			</tr>
		</table>


	</div>
</div>