<?php echo $this->form('translations');?>
<table class="styled">
<tr>
    <th><?php echo $this->translate('code'); ?></th>
    <?php foreach($this->languages as $language):?>
    	<td><?php echo $this->translate($language);?></td>
    <?php endforeach;?>	
    </tr>
<?php
foreach ($this->rows as $row) :
    ?>
<tr>

		<td><?php echo $row['msgid'];?></td>
	<?php foreach($this->languages as $language):?>
	<td><?php echo $this->formText('translation[' .$language. '][' . $row['msgid'].']',
	                              (isset($this->translations[$language][$row['msgid']]) ? $this->translations[$language][$row['msgid']] : ''), 
	                              array('placeholder' => $row['msgid'], 
                                        'class' => 'translation'));
if($this->googleTranslate){
?><a href="<?php echo $this->url(array('action' => 'googletranslate'));?>?name=<?php echo $row['msgid'];?>&language=<?php echo $language;?>" class="googleTranslate"><img alt="GTranslate" src="/img/google_translate.png"></a><?php
}
        ?>
    </td>
	<?php endforeach;?>
</tr>
<?php endforeach;?>
</table>
</form>
<?php $script = <<<EOF
    $(document).ready(function(){
        $('input.translation').change(function(){
//             alert($(this).attr('name'))
            var field = $(this);
            $.post('/admin/translations/add/', {value : $(this).val(), 'field' : $(this).attr('name')}, function (data) {
            if(data){
                field.addClass('resultGood');
            } else {
                field.addClass('resultBad');
            }})
        })
    $('a.googleTranslate').click(function(){
        element = $(this);
        url = $(this).attr('href');
        var translation = $.get(url, function(data){
            element.prev('input').val(data);
            element.prev('input').change();
        });

        return false;
    })

})

EOF;
$this->headScript()->appendScript($script);
?>