<div id="back_to_categories">
	<a
		href="<?PHP echo $this->url(array('vendor_id' => $this->vendor_id, 'model_id' => $this->model_id, 'typ_id' => $this->typ_id, 'str_id' => '10001'), 'parts-vendor-model-type-cat'); ?>"><?php echo $this->translate('Back to all categories');?></a>
</div>
<?php if(!empty($this->searchTreeSiblings)) :?>
<ul class="siblings">
<?php foreach($this->searchTreeSiblings as $sibling):?>
    <li<?php if($this->str_id == $sibling['STR_ID']):?> class="current"<?php endif;?>><a href="<?php echo $this->url(array('action' => 'type',
									'vendor_id' => $this->vendor_id, 
        							'model_id'=>$this->model_id,
        							'typ_id' => $this->typ_id,
        							'str_id' => $sibling['STR_ID'],
	        						'art' => true,
        								),
        							'parts-vendor-model-type-cat-art', true);?>"
        							 ><?php echo $sibling['STR_DES_TEXT'];?></a>
        							</li>
<?php endforeach;?>
</ul>
<?php endif;?>