<?php //echo $this->article['ART_ARTICLE_NR'];?>

<h2><?php echo $this->article['ART_COMPLETE_DES_TEXT'];?> (<?php echo $this->article['SUP_BRAND'];?>)</h2>
<div><?php echo $this->article['ART_DES_TEXT'];?></div>
<div><?php echo $this->article['params']['AIN_TMO_TEXT'];?></div>


<div>
<?php echo $this->itemPrice($this->article);?>
</div>

<?php if($this->article['image']){?>
<div>
	<img src="/<?php echo $this->article['image'];?>" />
</div>


<?php }?>
<div><a class="add_to_cart_button" href="/cart/itemAdd/item_id/<?php echo $this->art_id?>"><?php echo $this->translate('Add to cart')?></a></div>

<div id="article_criteria">
	<table>
	
	<?php foreach($this->article['criteria'] as $criteria){?>
	<tr>
		<td><?php echo $criteria['CRITERIA_DES_TEXT'];?></td>
		<td><?php echo $criteria['CRITERIA_VALUE_TEXT'];?></td>
	</tr>
	<?php }?>
	</table>
</div>
<div id="add_to_cart_modal"></div>
<?php $script = <<<EOF
$(document).ready(function(){
    modal = $('#add_to_cart_modal').dialog({autoOpen:false});
    $("input.itemAddToCart").click(function(){
       var form = $(this).parent('form');
	   formData = form.serialize();  
	   $.post(form.attr('action'), formData, function(data){
            modal.html(data).dialog('open')
        })
		        return false;
    })
})
EOF;
?>
<?php 
$this->headScript()->appendScript($script);
?>