<form action="" method="get">
<label>Degviela: <select name="fuel_type">
  <option>Benzīns</option>
  <option>Dīzelis</option>
  <option>Benzīns / Gāze</option>
	
</select>
</label>
<label>Gads: 
<select name="year" id="year">
	
</select></label>
<input type="submit" name="search" id="search" value="Atlasīt" />
</form>
<table border="1">
  <tr>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th colspan="2" scope="col">ražošanas laiks</th>
    <th scope="col">&nbsp;</th>
    <th colspan="2" scope="col">Jauda kW</th>
    <th colspan="2" scope="col">Jauda Zs</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
    <th scope="col">&nbsp;</th>
  </tr>
  <tr>
    <th scope="col">typ id</th>
    <th scope="col">Auto marka</th>
    <th scope="col">modelis</th>
    <th scope="col">nosaukums</th>
    <th scope="col">no</th>
    <th scope="col">līdz</th>
    <th scope="col">motora tilpums ccm</th>
    <th scope="col"> no</th>
    <th scope="col"> līdz</th>
    <th scope="col">no</th>
    <th scope="col">līdz</th>
    <th scope="col">cilindru skaits</th>
    <th scope="col">motora kods</th>
    <th scope="col">motora tips</th>
    <th scope="col">degviela</th>
    <th scope="col">uzbūve</th>
    <th scope="col">ass konstrukcija</th>
    <th scope="col">tonnāža</th>
  </tr>
  <?php
 foreach($this->types as $type){
	?>
  <tr>
    <td><a href="<?php echo $this->url(array(	'action' => 'type', 
            									'vendor_id' => $this->vendor_id, 
            									'model_id'=>$this->model_id, 
            									'typ_id' => $type['TYP_ID'], 
            									'str_id' => $this->str_id,
            										),
            									'parts-vendor-model-type-cat', true);?>"><?PHP echo $type['TYP_ID'];?></a></td>
    <td><?PHP echo $type['MFA_BRAND'];?></td>
    <td><?PHP echo $type['MOD_CDS_TEXT'];?></td>
    <td><?PHP echo $type['TYP_CDS_TEXT'];?></td>
    <td><?PHP echo $type['TYP_PCON_START'];?></td>
    <td><?PHP echo $type['TYP_PCON_END'];?></td>
    <td><?PHP echo $type['TYP_CCM'];?></td>
    <td><?PHP echo $type['TYP_KW_FROM'];?></td>
    <td><?PHP echo $type['TYP_KW_UPTO'];?></td>
    <td><?PHP echo $type['TYP_HP_FROM'];?></td>
    <td><?PHP echo $type['TYP_HP_UPTO'];?></td>
    <td><?PHP echo $type['TYP_CYLINDERS'];?></td>
    <td><?PHP echo $type['ENG_CODE'];?></td>
    <td><?PHP echo $type['TYP_ENGINE_DES_TEXT'];?></td>
    <td><?PHP echo $type['TYP_FUEL_DES_TEXT'];?></td>
    <td><?PHP echo $type['TYP_BODY_DES_TEXT'];?></td>
    <td><?PHP echo $type['TYP_AXLE_DES_TEXT'];?></td>
    <td><?PHP echo $type['TYP_MAX_WEIGHT'];?></td>
  </tr>
  <?php 
}?>
</table>
