
<table class="styled" cellspacing="0">

  <tr>
    <th scope="col"><?php echo $this->translate('id');?></th>
<!-- <th scope="col"><?php echo $this->translate('Vehicle brand');?></th>
    <th scope="col"><?php echo $this->translate('Vehicle model');?></th> -->
    <th scope="col"><?php echo $this->translate('Model Name');?></th>
    <th scope="col"><?php echo $this->translate('Production time');?></th>
    <th scope="col"><?php echo $this->translate('Engine');?></th>
    <th scope="col"><?php echo $this->translate('Power');?></th>

    <th scope="col"><?php echo $this->translate('Engine code');?></th>

  </tr>
  <?php
 foreach($this->types as $type){
	?>
  <tr>
    <td><a href="<?php echo $this->url(array(	'action' => 'type', 
            									'vendor_id' => $this->vendor_id, 
            									'model_id'=>$this->model_id, 
            									'typ_id' => $type['TYP_ID'], 
            									'str_id' => $this->str_id,
            										),
            									'parts-vendor-model-type-cat', true);?>"><?PHP echo $type['TYP_ID'];?></a></td>
 <!--    <td><?PHP echo $type['MFA_BRAND'];?></td>
    <td><?PHP echo $type['MOD_CDS_TEXT'];?></td> -->
    <td><?PHP echo $type['TYP_CDS_TEXT'];?></td> 
    <td><?PHP echo $this->Yearmonth($type['TYP_PCON_START'], $type['TYP_PCON_END']);?></td>
    <td><?PHP echo $type['TYP_CCM'];?> ccm</td>
    <td><?PHP echo $type['TYP_KW_FROM'] . 'kw / ' .  $type['TYP_HP_FROM'] . 'hp';?></td>

  <!--   <td><?PHP echo $type['TYP_CYLINDERS'];?></td>  -->
    <td><?PHP echo $type['ENG_CODE'];?></td>

  </tr>
  <?php 
}?>
</table>
