
<table border="0">
	<tr>
		<th scope="col"><?php echo $this->translate('Model');?></th>
		<th scope="col"><?php echo $this->translate('Year from');?></th>
		<th scope="col"><?php echo $this->translate('Year to');?></th>
		<th scope="col"><?php echo $this->translate('type');?></th>
	</tr>
<?php
foreach ($this->models as $model) {
    ?>  <tr>
		<td><a
			href="<?php echo $this->url(array('model_id' => $model['MOD_ID'], 'vendor_id' =>$this->vendor_id), 'parts-vendor-model', true);?>">
      <?php 	echo $model['MOD_CDS_TEXT'];?>
    </a></td>
		<td><?php echo $model['MOD_PCON_START'];?></td>
		<td><?php echo $model['MOD_PCON_END'];?></td>
		<td><?php echo ($model['MOD_PC'])?$this->translate('van'):$this->translate('heavy vehicle');?></td>
	</tr><?php
}
?>
</table>
