<div id="view-content">

<div class="client_information">
<?php if($this->loggedIn):?>
    <h4><?php echo $this->translate('Your information');?></h4>
    
    <?php echo $this->translate('first_name')?>: <?php echo $this->clientInformation->first_name;?><br />
    <?php echo $this->translate('last_name')?>: <?php echo $this->clientInformation->last_name;?><br />
    <?php echo $this->translate('email')?>: <?php echo $this->clientInformation->email;?><br />
    <?php echo $this->translate('country')?>: <?php echo $this->translate($this->clientInformation->country);?><br />
</div>

    
     <?php echo $this->form;?>
    <?php else:?>
        <?php echo $this->translate('You must login or register, to continue');?>
        <br />
        <div class="buttons">
        <a class="register" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'register'));?>"><?php echo $this->translate('Go to registration form')?></a>
        
        <a class="login" href="<?php echo $this->url(array('controller' => 'user', 'action' => 'login'));?>"><?php echo $this->translate('Go to login form')?></a>
        </div>
    <?php endif;?>

</div>

<?php $this->headStyle()->captureStart();?>
div.buttons a{
    position: relative;
    display: block;
    float: left;
    margin-top: 40px;
    margin-right: 20px;
    padding: 10px;
    background-color: #ccc;
    border: solid 1px #000;
    border-radius: 10px;
}
<?php $this->headStyle()->captureEnd(); ?>