<div id="information">
    <div class="client_information">
    <?php if($this->loggedIn):?>
        <h4><?php echo $this->translate('Your information');?></h4>
        <dl>
            <dt> <?php echo $this->translate('first_name')?>:</dt> <dd><?php echo $this->client->first_name;?></dd>
            <dt><?php echo $this->translate('last_name')?>:</dt> <dd><?php echo $this->client->last_name;?></dd>
            <dt><?php echo $this->translate('email')?>: </dt> <dd><?php echo $this->client->email;?></dd>
            <dt><?php echo $this->translate('country')?>: </dt> <dd><?php echo $this->translate($this->client->country);?></dd>
        </dl>
        <?php endif;?>
    </div>
    <?php if($this->company):?>
    <div class="company_information">
    	<h4><?php echo $this->translate('Company information'); ?></h4>
        <dl>
        <?php foreach($this->company as $key => $value):?>
        	<dt><?php echo $this->translate($key); ?></dt>
        	   <dd><?php echo $value;?></dd>
       <?php endforeach;?>
        </dl>
    </div>
    <?php endif;?>
    
    <div class="shipping_information">
    	<h4><?php echo $this->translate('Shipping information'); ?></h4>
    	    <dl>
        <?php foreach($this->shipping as $key => $value):?>
        	<dt><?php echo $this->translate($key); ?></dt>
        	   <dd><?php echo $value;?></dd>
       <?php endforeach;?>
        </dl>
    </div>
    <div class="clear"></div>
</div>
<div id="order_information">
    <?php echo $this->form('order_confirm', array('method' => 'post'));?>
	<table>
	    <tr>
    	<th><?php echo $this->translate('Item code');?></th>
    	<th><?php echo $this->translate('Brand');?></th>
    	<th><?php echo $this->translate('Item name');?></th>
    	<th><?php echo $this->translate('Count');?></th>
    	<th><?php echo $this->translate('Cost');?></th>
    </tr>
<?php 
    $totalCount = 0;
    $totalPrice = 0;
foreach($this->cartItems as $item):

    $totalCount += $item['count'];
    $totalPrice += ($item['price'] * $item['count']);
    ?>
    <tr>
       <!--  <td><?php echo $item['id'];?></td>  -->
        <td><?php echo $item['code']?></td>
        <td><?php echo $item['brand']?></td>
        <td><?php echo $item['name']?></td>
        <td><?php echo $item['count'];?></td>
        <td align="center"><?php echo $this->currency($item['price'], 'NOK');?></td>
    </tr>
    
    <?php

    endforeach;

    ?>
    <tr>
<!--     	<td></td> -->
    	<td></td>
    	<td></td>
    	<td align="right"><strong><?php echo $this->translate('Total');?>:</strong></td>
    	<td><strong><?php echo $totalCount;?></strong></td>
    	<td><strong><?php echo $this->currency($totalPrice, 'NOK')  ;?></strong></td>
    </tr>
   <tr>
<!--        <td></td> -->
       <td></td>
       <td></td>
       <td></td>
       <td><?php echo $this->translate('Have read and accept');?> <a target="_blank" id="terms" href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'terms'), 'article-read');?>"><?php echo $this->translate('terms'); ?><?php echo $this->formCheckbox('accept_terms', 1);?></a></td>
       <td><?php echo $this->formSubmit('Submit', 'Place order', array('class' => 'place_order'));?></td>
   </tr>
    </table>
    </form>
</div>

<?php $this->headStyle()->captureStart();?>
div#information div{
    width: 33%;
    position: relative;
    float: left;
}
a#terms {
    text-decoration: underline;
    color: red;
}
input[type=submit].place_order {
    padding: 10px;
    font-weight: bold;
}
<?php $this->headStyle()->captureEnd(); ?>