<?php echo $this->doctype()?>
<html>
<head>

    <?php echo $this->headMeta(); ?>
    
<?php  $this->headLink()->appendStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/smoothness/jquery-ui.css') ?>
<?php  $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js');?>
<?php  $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js');?>

    <?php echo $this->headScript();?>
<?php echo $this->headLink();?>
  <title>Car Parts ADMIN</title>
  <?php echo $this->headLink()->appendStylesheet('/css/adminWithStyle.css')?>
</head>
<body>
	<div id="header" style="background-color: #EEEEEE; height: 30px;">
		<div id="header-logo" style="float: left">
			<b><?php $this->layout()->menu; ?></b>
		</div>
		<div id="header-navigation" style="float: right">
			<a
				href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'orders', 'action' => 'index'));?>">Orders</a>
			<a
				href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'articles', 'action' => 'index'));?>">Articles</a>
			<a
				href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'menu', 'action' => 'index'));?>">Menu</a>
			<a
				href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'system', 'action' => 'index'));?>">System</a>
			<a
				href="<?php echo $this->url(array('module'=>'admin', 'controller' => 'translations', 'action' => 'index'));?>">Translations</a>
		</div>
	</div>
	<div id="content">
    <?php echo $this->layout()->content?>
</div>
</body>
</html>