<?php echo $this->doctype('HTML5')?>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>BilParts</title>
<?php  $this->headLink()->appendStylesheet('/css/global.css') ?>
<?php  $this->headLink()->appendStylesheet('http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/themes/smoothness/jquery-ui.css') ?>
<?php  $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.2/jquery-ui.min.js');?>
<?php  $this->headScript()->prependFile('http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js');?>

<?php echo $this->headScript();?>
<?php echo $this->headLink();?>
<?php echo $this->headStyle();?>
</head>
<body>
<div id="header">
  <div id="language_bar"> 
   <?php if($this->loggedIn !== true):?>
       <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'login'), 'default');?>" id="SIGNIN"><?php echo $this->translate('Sign in'); ?></a> 
       <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'register'), 'default');?>" id="JOIN"><?php echo $this->translate('Join'); ?></a>
   <?php ?>
   <?php else: ?>
    <?php echo $this->translate('Logged in as')?> <a href="<?php echo $this->url(array('controller' => 'user', 'action' => 'logout'), 'default');?>">[<?php echo $this->translate('exit')?>]</a>
   <?php endif;?>
       <a href="<?php echo sprintf($this->languageLink, 'no');?>"><img src="/img/flag_no.png" alt="NO" width="22" height="16" class="language"></a> 
       <a href="<?php echo sprintf($this->languageLink, 'sv');?>"><img src="/img/flag_SW.png" alt="SV" width="22" height="16" class="language"></a> 
       <a href="<?php echo sprintf($this->languageLink, 'ru');?>"><img src="/img/flag_RU.png" alt="RU" width="22" height="16" class="language"></a> 
       <a href="<?php echo sprintf($this->languageLink, 'nl');?>"><img src="/img/flag_NL.png" alt="NL" width="22" height="16" class="language"></a> 
       <a href="<?php echo sprintf($this->languageLink, 'fi');?>"><img src="/img/flag_FI.png" alt="FI" width="22" height="16" class="language"></a> 
       <a href="<?php echo sprintf($this->languageLink, 'da');?>"><img src="/img/flag_DE.png" alt="DA" width="22" height="16" class="language"></a> 
       <a href="<?php echo sprintf($this->languageLink, 'en');?>"><img src="/img/flag_gb.png" alt="EN" width="22" height="16" class="language"></a> 

   </div>
  <div id="top_menu">
      <a href="/"><?php echo $this->translate('Home'); ?></a> 
      <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'aboutUs'), 'article-read', true);?>"><?php echo $this->translate('About us'); ?></a>
      <a href="/parts/<?php //echo $this->url(array('controller' => 'parts'));?>"><?php echo $this->translate('Products'); ?></a>
      <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'Partners'), 'article-read', true);?>"><?php echo $this->translate('Partners'); ?></a>
      <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'Services'), 'article-read', true);?>"><?php echo $this->translate('Services'); ?></a>
      <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'contacts'), 'article-read', true);?>"><?php echo $this->translate('Contacts'); ?></a>
      <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'shipping'), 'article-read', true);?>"><?php echo $this->translate('Shipping'); ?></a>
      <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'regulations'), 'article-read', true);?>"><?php echo $this->translate('Regulations'); ?></a>
      <a href="<?php echo $this->url(array('controller' => 'article', 'action' => 'read', 'article_alias' => 'payment'), 'article-read', true);?>"><?php echo $this->translate('Payment'); ?></a>
      
  </div>
  <div id="cart"><a href="/cart/"><img src="/img/cart.png" width="20" height="20" alt="Cart"><?php echo $this->translate('items in cart') . ': '?><span id="cartItemcount"><?php echo $this->cart->getItemCount();?></span></a></div>
  
  
  <div id="header-logo"><a href="/"><img src="/img/logo_plus.png" width="544" height="134" alt="Logo"></a> </div>
  <div id="model_panel">
  	<div id="model_form"><?PHP echo $this->formModel; ?></div>
  </div>
  <div id="header-navigation" style="float: right"> </div>
</div>
<div id="content"> <?php echo $this->layout()->content ?> </div>
</body>
</html>
