<?php if(isset($this->order)):?>

<div id="information">
    <div class="client_information">
    <?php if($this->loggedIn):?>
        <h4><?php echo $this->translate('Client information');?></h4>
        <dl>
            <dt> <?php echo $this->translate('first_name')?>:</dt> <dd><?php echo $this->client->getFirstName();?></dd>
            <dt><?php echo $this->translate('last_name')?>:</dt> <dd><?php echo $this->client->getLastName();?></dd>
            <dt><?php echo $this->translate('email')?>: </dt> <dd><?php echo $this->client->getEmail();?></dd>
            <dt><?php echo $this->translate('country')?>: </dt> <dd><?php echo $this->translate($this->client->getCountry());?></dd>
        </dl>
        <?php endif;?>
    </div>
    <?php if($this->company):?>
    <div class="company_information">
    	<h4><?php echo $this->translate('Company information'); ?></h4>
        <dl>
        <?php foreach($this->company as $key => $value):?>
        	<dt><?php echo $this->translate($key); ?></dt>
        	   <dd><?php echo $value;?></dd>
       <?php endforeach;?>
        </dl>
    </div>
    <?php endif;?>
    
    <div class="shipping_information">
    	<h4><?php echo $this->translate('Shipping information'); ?></h4>
    	    <dl>
        <?php foreach($this->shipping as $key => $value):?>
        	<dt><?php echo $this->translate($key); ?></dt>
        	   <dd><?php echo $value;?></dd>
       <?php endforeach;?>
        </dl>
    </div>
    <div class="clear"></div>
</div>
<div id="order_information">
    <?php echo $this->form('order_confirm', array('method' => 'post'));?>
	<table>
	    <tr>
    	<th><?php echo $this->translate('Item code');?></th>
    	<th><?php echo $this->translate('Brand');?></th>
    	<th><?php echo $this->translate('Item name');?></th>
    	<th><?php echo $this->translate('Count');?></th>
    	<th><?php echo $this->translate('Cost');?></th>
    </tr>
<?php 
    $totalCount = 0;
    $totalPrice = 0;
foreach($this->order_items as $item):

    $totalCount += $item->getAmount();
    $totalPrice += ($item->getPrice() * $item->getAmount());
    $tdInfo = $item->getTdInfo();
    ?>
    <tr>
		<td><?php echo $tdInfo['ART_ARTICLE_NR'];?></td>
		<td><?php echo $tdInfo['SUP_BRAND'];?></td>
		<td><?php echo $tdInfo['ART_COMPLETE_DES_TEXT'];?></td>
		<td><?php echo $item->getAmount();?></td>
        <td align="center"><?php echo $this->currency($item->getPrice(), 'NOK');?></td>
    </tr>
    
    <?php

    endforeach;

    ?>
    <tr>
<!--     	<td></td> -->
    	<td></td>
    	<td></td>
    	<td align="right"><strong><?php echo $this->translate('Total');?>:</strong></td>
    	<td><strong><?php echo $totalCount;?></strong></td>
    	<td><strong><?php echo $this->currency($totalPrice, 'NOK')  ;?></strong></td>
    </tr>
   <tr>
<!--        <td></td> -->
       <td></td>
       <td></td>
       <td></td>
       <td></td>
       <td></td>
   </tr>
    </table>
    </form>
</div>


<?php else: ?>
<?php echo $this->translate('Order not found'); ?>
<?php endif;?>


<?php $this->headStyle()->captureStart();?>

a#terms {
    text-decoration: underline;
    color: red;
}
input[type=submit].place_order {
    padding: 10px;
    font-weight: bold;
}
<?php $this->headStyle()->captureEnd(); ?>
